apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:i5cKDvQfQ3C1ZmUKuOk=,iv:wjSjIwSoLZ0zpe6G3vIHewjcAUal/2nXpKxH4FpwikM=,tag:tSK5Txn2aoaKXwueLCzrmQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:uwOWd1MTQimaNmCrrD701eDcbl7CJeiPl5+gELBi74QKcWnRgQ==,iv:v3c3Bkw3ndSwxawFSZmSue9usR/srBKLLzjGojeejn8=,tag:axpx0c2RMlRD/ePdDNqGwA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:QpmIUlPgCpDhlz1dlDMvjg==,iv:2fY6c2WUL1/f4fBh+ZUrNtbiZ84pGhF1/u2D2gKWDyA=,tag:ITW/42rkeuns6+D7itOXKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLME45bmlPTDNlRlRDcFRs
            YS9RMVdpYlNRME5zVlpXQnEvMkxOaFI0UlR3CnJzbHUyamZoSElDRk5ibTVZRThn
            eHY4MWR0a3RLRG9SUUYrbUhWZHQ2Y2MKLS0tICtzSmtOTi9kUnRqWDJvTDZOa09y
            SVVnSUhmZFN6b0hPNjNMTWlCUVl6dzAK32URSk4o8+BpGZ6o21zn08SK3rvk2KTj
            kZrOTYAkBEwJm567KF3SwniHlAUy0ENTr95Bd+gkYqFCRitfUrEjqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T15:59:38Z"
    mac: ENC[AES256_GCM,data:mKQ7CsVJolcE0NzfvTq4RGKLPE6aqr6uacDf2NvYwcMnqEYna++K+4cOCTprfyGFovzrcRnIMOGn4lPnTILgK+w7eSEqHEcL0MYaPaV+L7hgx3l670DSFh/un+HCV8P2RP1AOs6kkDlHFpJeNA7hvh2OzQuAkCSHKVtHcc191Bw=,iv:mCmxraPLUun6Qlhp3k8sMn5PIUu/LEf9VErc4ffQPY8=,tag:+adUsen9YHtwJWJMVZ0bvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
