---
version: '3'
vars:
  KUBERNETES_DIR: "{{.PWD}}/kubernetes"

includes:
  an: '.tasks/AnsibleTasks.yml'
  cl: '.tasks/ClusterTasks.yml'
tasks:
  bootstrap:
    cmds:
      - echo "{{.PWD}}/kubernetes"