---
- name: update hosts
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: install snap
  ansible.builtin.apt:
    name: snap
    state: present

- name: install microk8s
  community.general.snap:
    name: microk8s
    classic: yes
    state: present

- name: wait microk8s ready
  ansible.builtin.command:
    cmd: microk8s status --wait-ready
    
- name: configure user
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    group: microk8s
    append: yes


  
# sudo usermod -a -G microk8s $USER
# sudo chown -f -R $USER ~/.kube
# microk8s enable dns
# 
