apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:p/Lg10zQDlL268joUqNvuq8H/G7a+J+lSDfAPQA56oAN7ZcsEw==,iv:GLvyIejrajlspphWClXsh9m6ymqNQP7uJhst+WxymOQ=,tag:jcpTd7lmyEAENW1OYdhMIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNWU3N3ErTVNpSXM4YUZw
            WktOVXdzRFBlOEk0TkVISEYrNkJMSUhybTJrClFORGozUHNMMllZWmUwelVuOGhI
            VVJQUXdtOWxIYWNSV0o0dnEwcFdiakEKLS0tIFhxeXd4Z1F2T0xLN0E0SktCNWp0
            TUR5U2dGL0toZ0UzaUlqSWpxUmRTak0Klm3qwv6TfGAKQ8i0qzbu6P7bDiRJsYyw
            M3aHb0Pg2krERpbEazooqrnFl0N3/zUJQuc4oO2Y7djvXbdQENWqIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T03:03:02Z"
    mac: ENC[AES256_GCM,data:fFtke0Isgbjiwr38vIDfXI/5eKbHGTBHNoMrecOOlFdNnrYtK8RKUyEH5weqy6kkj/WnmOpbelHRY1sClJf+dUj09v7z+sj8PkVyF36z0p6bLZEak5Z0zwzScq8WOG23UAQAbR7YggroyrmbwbBToyAm7aRsx1MuHThKYZoXDNk=,iv:e8pMXmUvGHE1NOQl3Y4YRPbzwjkJNsYTGLF977sLaO0=,tag:b7GUG8+D5PAfKnmRWsmTgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
