apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:/0cKZS0xHUEmLla8a526HrsprJpJYymNw70PfwmFiL2VtKbATA==,iv:Lpt8zoFs2x3Gr/1ZR8hPOJr8VzV32Fb2N5DQ2JMy5gg=,tag:Qm7QB63QbXdWMo5YUW2xoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcFVXS0UveEt3aFJmY3Zx
            K053UnhvTmZIVVFCOHY1MUxiN1JwYlczS3pzCkJMdlY2ckoxZDBMb2gxTm94d1Y5
            SGsrQkNEMm5lc1pTYU1LZ2YybmNYMHcKLS0tIFB2bzFWNWdNd3JOS2VtSlVNYkFy
            a3ZIaEV0ZElydUs4ZENsaWQweDZlb1UK7TODdtg9gWwAe81HhS/iieEoVD8Gw9Ye
            3adnpXeOo7os1Vz8mvYYKrrCFfh6PbRx011qjfcleDv5w2Y0jlz3rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T15:59:38Z"
    mac: ENC[AES256_GCM,data:F0k/hEmt3UqiQ3RhWNtH3RgzZZqa16UJnxx4UCVs9lRXXWMkG3gw2Gd+OOpV9C7MBPkWoor2T8gpz4L0nMZ+y0Mnqy58SO52+n0rXqXvzL7W6BC7uSekRHiOPaFiy2o1X1X8oNRqlI1HNLvgCZANVAyMn/OR+axmUUYs+Eiwzpw=,iv:3zXtKcBMvNR0kRKXTN6YcmmOjvZog/rxulDZ7ZSyrO0=,tag:9jLGMZcI9EOQBBs2eNOqGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
