apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fTiAl9TNSzbZCnE=,iv:fOh3zbDvXX/ksW9BmyLpkTrKD7SwuQPeyZwBJOo4rMs=,tag:eN0+1vmuJJ3k0Xf99HYLrA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6OHo+O2cWK5YrSKb7cY=,iv:FIkz6xk8JKOiGftL7cPA4IKztKwP57U+ItJPq2Ia2ck=,tag:kIPn0cBDqVyA0kZ6hhTnhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa1dhdG9XcFk5UVNva1ls
            Qms5S1BJT0F6Z3hsenprZ2FoS2FKN05SMmd3CnBMVjBSM2RrZTc1NXN5MzJVSjJ6
            ODBuU1AyT2FrV1NXajBISlJDQ20xWUEKLS0tIDI1aVpncFZEYWxRTWhXbU1ubWtK
            VlhlNFFnRU85aWlNTitOdzJrOG0vN28KzPSMEglKGXxX2ZoGow+27ZSA3q3NcODp
            WgJ5ZJns3Ybb9tZ+Ao/Q+DphYUsamkrM1AgesB2BovY5WOvwd76uVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T15:59:38Z"
    mac: ENC[AES256_GCM,data:RHqlaAmpZn5pVH36wT/vWSRodh2GnniUcJEFi/yYJvrIC/jbFpNeRnwfc2yK8n33sy2hkKbJsz7cVs2FHmZw/TSXYSHACzVVdmUpqzRfEhp1oh6N7o41o2bdDMRzViRSiTx0TJblbMpUr2CQe6yKstELZ3+HJwd7LtsSSj++WBY=,iv:nVquFLAa4uNPGWj/xkTNAhxhzaRhTAjUqSG6pESfq0c=,tag:yB4dUZy1NR7oqoFc7waTGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
