---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Asia/Makassar"
  KUBE_VIP_ADDR: "10.132.145.254"
  METALLB_LB_RANGE: "10.132.145.220-10.132.145.230"
  METALLB_K8S_GATEWAY_ADDR: "10.132.145.220"
  METALLB_INGRESS_ADDR: "10.132.145.221"
