kind: ENC[AES256_GCM,data:KeKPJtgW,iv:Ry5ECK8/8RDIMIOONji0nGdgcOtTjQHCiUkPgl/MfEk=,tag:rpQuJ8Prsq4SPJrxjZnV7w==,type:str]
ansible_user: ENC[AES256_GCM,data:tEf+MyxI,iv:Mq5VqQbF3mqWrVaP4bRni2QMl2U7G0bEC3SKeF2jql0=,tag:YVWU/AOSDibHskr3XJwDxg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xo2aXeRMbCPY859m,iv:XUovQLngXsCn2uwk5Y4kQ/EH4lBKiau8E5yJOp6HIwA=,tag:OT2FKFRYBVQg2jLBB1sRZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R0dqQzlOS1F4UVhmaHps
            anRRd01adE5WOHdlMlJoZ2piMHZjVGhGMVhjCms3UHdid0lUYWhtcm9SREwrY0V5
            Njc0K0hpT240WVBneVZGSWdIcE8rNDgKLS0tIDdIM1V6TDBud2NqcGdDQVNpRVM2
            ZE5VbDJ5dkEyOWQ0Ni9wVFllNXY5dnMKnQpAP0iM9O+gtX9DzNI7V6Vb8lYIWJyA
            k+SjYMtSoxev632ESuOPy9U+ZHlPdIU81c3bCCbC2lP3W9Y6/bt6ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T17:05:44Z"
    mac: ENC[AES256_GCM,data:CKW0ZuXyfR/FD4pAjS5iIQud6zys7WooGNhCAKxkAOK5o9uVe6+ko3sQWAH1krVWroDoyhON9izH7eKfMOs8fd5U4znWwSh6Vt4UfFG5mnd670EEmlbC5Xn0zbO1682b97bzGDm+yoJOQOMqZcHFXPGENW92PdTVRLufWyPI3w8=,iv:c0Rtm3BwlK1zDshCkl61xZ+ZqPH7DhNFW+om/ms7p+0=,tag:ahZgOIESsuf1PbzpoNZNxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
