---
- name: update servers
  hosts: servers
  become: true
  roles:
    - common

- name: build master
  become: true
  hosts: master
  tasks:
    - name: enable dns
      ansible.builtin.command:
        cmd: 'microk8s enable dns hostpath-storage'

    - name: add node
      ansible.builtin.command:
        cmd: 'microk8s add-node'

    - name: generate configuration file
      ansible.builtin.command:
        cmd: 'microk8s config > /home/{{ansible_user}}/kubeconfig'

    - name: Get absolute path to this Git repository
      delegate_to: localhost
      become: false
      run_once: true
      check_mode: false
      ansible.builtin.command: |-
        git rev-parse --show-toplevel
      register: repo_abs_path

    - name: copy kubeconfig into project directory
      ansible.builtin.fetch:
        src: '/home/{{ansible_user}}/kubeconfig'
        dest: "{{ repo_abs_path.stdout }}/kubeconfig"
        flat: true

    - name: create master cluster node
      ansible.builtin.command:
        cmd: 'microk8s add-node'